name: SonarCloud - Backend Focused

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - backend/**
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: suasenha
          MYSQL_DATABASE: EcoNet_DB
        ports:
          - 3307:3306
        options: > 
          --health-cmd="mysqladmin ping -h 127.0.0.1" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=10

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            mysqladmin ping -h "127.0.0.1" -P 3307 --silent && break;
            echo "Waiting for MySQL...";
            sleep 2;
          done

      - name: Run tests
        env:
          DB_HOST: localhost
          DB_PORT: 3307
          DB_USER: root
          DB_PASSWORD: suasenha
          DB_NAME: EcoNet_DB
        run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=FGA0138-MDS-Ajax_2025.1-Algiz
            -Dsonar.organization=fga-mds-ajax
            -Dsonar.host.url=https://sonarcloud.io
